name: deploy website preview
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up pr preview
        uses: amondnet/vercel-action@v20 # deploy
        id: vercel-action-staging
        if: github.event_name == 'pull_request'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-org-id: ${{ secrets.ORG_ID }} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required
          working-directory: ./
          github-comment: false

      - name: set up production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
          vercel-args: "--prod" # Optional
          github-comment: false

      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
